In [741]:
import pandas as pd 
import numpy as np 
import sklearn 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [742]:
df1 = pd.read_csv("C:/train2.csv") 
df1.head(500)

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81,critical_temperature
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.11900,20.285800,36.105357,...,4.100000,4.053600,3.944244,1.339718,1.245504,3,1.400000,1.299038,1.135782,21.50
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.98100,25.192187,67.233835,...,2.400000,2.402249,2.259897,1.519383,1.365077,3,0.933333,1.200000,1.019804,62.00
2,2,23.035850,26.647510,21.192566,25.010514,0.614232,0.435817,18.05830,18.243490,9.029150,...,5.100000,4.242641,4.873514,0.636514,0.465999,3,3.300000,1.500000,1.374773,0.29
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.48200,28.789976,32.890369,...,3.620000,3.309751,3.413039,1.333736,1.019322,3,1.920000,1.118034,1.198165,19.50
4,2,67.485250,69.699016,57.442709,59.574464,0.548263,0.521345,70.84050,39.638078,35.420250,...,6.000000,6.000000,6.000000,0.693147,0.691193,0,0.375000,0.000000,0.000000,5.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,6,79.740817,57.288771,61.580623,37.884226,1.555680,1.435489,184.59060,21.171332,58.029604,...,2.150000,2.401874,2.084117,1.667462,1.423635,4,0.975000,1.490712,0.759934,18.00
496,4,76.444563,52.802729,59.356672,36.161551,1.199541,1.284861,121.32760,14.919530,43.823354,...,2.080321,2.213364,2.066207,1.368922,1.224135,1,0.795181,0.433013,0.271790,45.40
497,1,207.200000,207.200000,207.200000,207.200000,0.000000,0.000000,0.00000,0.000000,0.000000,...,4.000000,4.000000,4.000000,0.000000,0.000000,0,0.000000,0.000000,0.000000,7.22
498,5,85.993480,56.414050,65.721060,36.447479,1.402550,1.381420,141.25060,20.482865,52.961521,...,2.088462,2.352158,2.073038,1.589027,1.262734,1,1.042308,0.489898,0.283965,47.00
499,4,60.430908,60.430908,44.279257,44.279257,1.099857,1.099857,122.90607,30.726517,47.489919,...,3.250000,3.080070,3.080070,1.332245,1.332245,3,0.750000,1.089725,1.089725,5.80

In [743]:
df2 = pd.read_csv("C:/test2.csv")
df2.head(500)

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature72,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81
0,5,82.324574,88.533544,64.110667,72.640059,1.418486,1.179961,122.90607,38.757614,48.331141,...,2.400000,2.151429,2.352158,2.126646,1.589027,1.361750,1,0.814286,0.489898,0.358466
1,4,115.438500,90.562624,107.211420,88.713057,1.308571,1.157701,122.45400,37.743936,47.516249,...,4.000000,3.632000,3.722419,3.504866,1.320888,1.064083,4,1.504000,1.414214,0.853567
2,4,92.290900,83.842290,87.295606,79.318618,1.331889,1.300022,81.48200,20.872340,30.558629,...,4.000000,3.870000,3.662842,3.611896,1.305096,1.193165,4,1.600000,1.581139,1.361286
3,5,72.324650,51.227894,58.637102,34.924853,1.444612,1.306314,121.32760,20.998358,40.053512,...,2.400000,2.079231,2.352158,2.065294,1.589027,1.219461,1,1.070000,0.489898,0.270099
4,4,90.142263,58.462879,66.935044,36.272055,1.178649,1.019134,124.90825,34.237393,53.101375,...,3.000000,2.571429,2.828427,2.438027,1.329661,1.083356,2,1.057143,1.000000,0.903508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,3,120.376000,123.054577,120.258556,122.967486,1.097631,0.805699,12.78200,60.431001,5.349551,...,4.333333,4.973340,4.160168,4.859058,1.057905,0.748371,3,2.920020,1.247219,1.047558
496,4,94.036450,66.769629,65.686358,38.311392,1.100637,1.144121,192.98100,31.198486,71.191171,...,2.750000,2.528169,2.514867,2.350119,1.288252,1.188147,3,0.943662,1.299038,1.142604
497,5,83.244760,58.395869,59.506081,35.593199,1.311510,1.378715,192.98100,24.627824,67.233835,...,2.600000,2.395231,2.402249,2.256608,1.519383,1.362904,3,0.932877,1.200000,1.014635
498,5,63.224881,74.326485,45.321982,56.471073,1.320880,1.178499,134.36060,37.305024,48.928585,...,2.800000,3.235000,2.459509,3.048212,1.494403,1.350366,4,1.235000,1.326650,1.113452
499,2,48.739250,15.508657,32.039477,13.187149,0.373280,0.575581,73.45710,7.368867,36.728550,...,2.500000,3.857143,2.000000,3.744471,0.500402,0.066522,3,3.761905,1.500000,0.638877

In [744]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 82 columns):
feature1                17000 non-null int64
feature2                17000 non-null float64
feature3                17000 non-null float64
feature4                17000 non-null float64
feature5                17000 non-null float64
feature6                17000 non-null float64
feature7                17000 non-null float64
feature8                17000 non-null float64
feature9                17000 non-null float64
feature10               17000 non-null float64
feature11               17000 non-null float64
feature12               17000 non-null float64
feature13               17000 non-null float64
feature14               17000 non-null float64
feature15               17000 non-null float64
feature16               17000 non-null float64
feature17               17000 non-null float64
feature18               17000 non-null float64
feature19               17000 non-null float64
feature20               17000 non-null float64
feature21               17000 non-null float64
feature22               17000 non-null float64
feature23               17000 non-null float64
feature24               17000 non-null float64
feature25               17000 non-null float64
feature26               17000 non-null float64
feature27               17000 non-null float64
feature28               17000 non-null int64
feature29               17000 non-null float64
feature30               17000 non-null float64
feature31               17000 non-null float64
feature32               17000 non-null float64
feature33               17000 non-null float64
feature34               17000 non-null float64
feature35               17000 non-null float64
feature36               17000 non-null float64
feature37               17000 non-null float64
feature38               17000 non-null float64
feature39               17000 non-null float64
feature40               17000 non-null float64
feature41               17000 non-null float64
feature42               17000 non-null float64
feature43               17000 non-null float64
feature44               17000 non-null float64
feature45               17000 non-null float64
feature46               17000 non-null float64
feature47               17000 non-null float64
feature48               17000 non-null float64
feature49               17000 non-null float64
feature50               17000 non-null float64
feature51               17000 non-null float64
feature52               17000 non-null float64
feature53               17000 non-null float64
feature54               17000 non-null float64
feature55               17000 non-null float64
feature56               17000 non-null float64
feature57               17000 non-null float64
feature58               17000 non-null float64
feature59               17000 non-null float64
feature60               17000 non-null float64
feature61               17000 non-null float64
feature62               17000 non-null float64
feature63               17000 non-null float64
feature64               17000 non-null float64
feature65               17000 non-null float64
feature66               17000 non-null float64
feature67               17000 non-null float64
feature68               17000 non-null float64
feature69               17000 non-null float64
feature70               17000 non-null float64
feature71               17000 non-null float64
feature72               17000 non-null float64
feature73               17000 non-null float64
feature74               17000 non-null float64
feature75               17000 non-null float64
feature76               17000 non-null float64
feature77               17000 non-null float64
feature78               17000 non-null int64
feature79               17000 non-null float64
feature80               17000 non-null float64
feature81               17000 non-null float64
critical_temperature    17000 non-null float64
dtypes: float64(79), int64(3)
memory usage: 10.6 MB

In [745]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4263 entries, 0 to 4262
Data columns (total 81 columns):
feature1     4263 non-null int64
feature2     4263 non-null float64
feature3     4263 non-null float64
feature4     4263 non-null float64
feature5     4263 non-null float64
feature6     4263 non-null float64
feature7     4263 non-null float64
feature8     4263 non-null float64
feature9     4263 non-null float64
feature10    4263 non-null float64
feature11    4263 non-null float64
feature12    4263 non-null float64
feature13    4263 non-null float64
feature14    4263 non-null float64
feature15    4263 non-null float64
feature16    4263 non-null float64
feature17    4263 non-null float64
feature18    4263 non-null float64
feature19    4263 non-null float64
feature20    4263 non-null float64
feature21    4263 non-null float64
feature22    4263 non-null float64
feature23    4263 non-null float64
feature24    4263 non-null float64
feature25    4263 non-null float64
feature26    4263 non-null float64
feature27    4263 non-null float64
feature28    4263 non-null int64
feature29    4263 non-null float64
feature30    4263 non-null float64
feature31    4263 non-null float64
feature32    4263 non-null float64
feature33    4263 non-null float64
feature34    4263 non-null float64
feature35    4263 non-null float64
feature36    4263 non-null float64
feature37    4263 non-null float64
feature38    4263 non-null float64
feature39    4263 non-null float64
feature40    4263 non-null float64
feature41    4263 non-null float64
feature42    4263 non-null float64
feature43    4263 non-null float64
feature44    4263 non-null float64
feature45    4263 non-null float64
feature46    4263 non-null float64
feature47    4263 non-null float64
feature48    4263 non-null float64
feature49    4263 non-null float64
feature50    4263 non-null float64
feature51    4263 non-null float64
feature52    4263 non-null float64
feature53    4263 non-null float64
feature54    4263 non-null float64
feature55    4263 non-null float64
feature56    4263 non-null float64
feature57    4263 non-null float64
feature58    4263 non-null float64
feature59    4263 non-null float64
feature60    4263 non-null float64
feature61    4263 non-null float64
feature62    4263 non-null float64
feature63    4263 non-null float64
feature64    4263 non-null float64
feature65    4263 non-null float64
feature66    4263 non-null float64
feature67    4263 non-null float64
feature68    4263 non-null float64
feature69    4263 non-null float64
feature70    4263 non-null float64
feature71    4263 non-null float64
feature72    4263 non-null float64
feature73    4263 non-null float64
feature74    4263 non-null float64
feature75    4263 non-null float64
feature76    4263 non-null float64
feature77    4263 non-null float64
feature78    4263 non-null int64
feature79    4263 non-null float64
feature80    4263 non-null float64
feature81    4263 non-null float64
dtypes: float64(78), int64(3)
memory usage: 2.6 MB

In [746]:
feature_names = df1.columns.tolist() 
for column in feature_names: 
    print(column) 
    print(df1[column].value_counts(dropna=False))

feature1
5    4612
4    3587
3    3159
2    2604
6    2149
7     600
1     229
8      49
9      11
Name: feature1, dtype: int64
feature2
76.444563     580
76.517718     281
83.244760     261
74.231650     209
89.337180     191
             ...
160.886467      1
118.522284      1
111.036057      1
94.569160       1
115.285500      1
Name: feature2, Length: 3108, dtype: int64
feature3
51.245665     86
59.224400     67
81.456750     41
56.808817     39
15.309000     37
              ..
91.993943      1
91.578540      1
49.158722      1
75.407444      1
120.515408     1
Name: feature3, Length: 12558, dtype: int64
feature4
59.356672     580
59.310096     281
59.506081     261
60.515221     209
70.560647     191
             ...
55.898574       1
158.615479      1
51.756309       1
77.174634       1
47.258519       1
Name: feature4, Length: 3108, dtype: int64
feature5
34.935266     86
36.126175     67
68.229617     41
35.773432     39
14.162583     37
              ..
21.830901      1
118.231830     1
61.041783      1
116.303328     1
57.556783      1
Name: feature5, Length: 12559, dtype: int64
feature6
1.199541    580
1.197273    281
1.311510    261
0.000000    229
1.453747    209
           ...
0.665190      1
1.311755      1
1.379590      1
1.439362      1
1.429644      1
Name: feature6, Length: 3061, dtype: int64
feature7
0.000000    229
1.291888     86
1.372050     67
1.108189     41
0.981880     39
           ...
1.377721      1
0.675772      1
1.509344      1
0.229771      1
1.388945      1
Name: feature7, Length: 12511, dtype: int64
feature8
121.327600    1691
192.981000    1636
122.906070    1409
128.242600     564
188.383900     483
              ...
62.827500        1
156.258500       1
177.600231       1
34.013600        1
91.666600        1
Name: feature8, Length: 980, dtype: int64
feature9
0.000000     229
36.950657    161
12.512169    119
50.245175    101
14.288319     86
            ...
39.397000      1
11.700938      1
77.173489      1
15.038565      1
37.451100      1
Name: feature9, Length: 10594, dtype: int64
feature10
43.823354    580
44.289459    281
67.233835    261
0.000000     229
39.445875    209
            ...
13.438900      1
33.086531      1
54.183098      1
48.955677      1
56.510200      1
Name: feature10, Length: 3060, dtype: int64
feature11
0.000000     229
44.192125     86
64.196304     67
40.612293     41
52.533207     39
            ...
40.595826      1
2.576432       1
43.610200      1
38.320639      1
30.493078      1
Name: feature11, Length: 12454, dtype: int64
feature12
794.000000    580
787.050000    281
779.880000    261
816.360000    209
740.520000    191
             ...
733.033333      1
683.866667      1
687.566667      1
747.416667      1
748.150000      1
Name: feature12, Length: 2785, dtype: int64
feature13
1003.623077    86
1005.866667    67
738.357143     41
1011.540714    39
779.233333     37
               ..
1010.715229     1
575.200000      1
1012.527165     1
642.799500      1
684.978000      1
Name: feature13, Length: 12394, dtype: int64
feature14
741.629349    580
734.219624    281
740.399333    261
771.891022    209
692.541331    191
             ...
641.673655      1
693.536674      1
708.200418      1
797.799281      1
678.981683      1
Name: feature14, Length: 3035, dtype: int64
feature15
937.559192     86
945.371396     67
702.424197     41
940.294344     39
778.658644     37
               ..
753.319058      1
1029.903188     1
846.462261      1
936.491919      1
710.355945      1
Name: feature15, Length: 12502, dtype: int64
feature16
1.315004    580
1.313008    281
1.553219    261
0.000000    229
1.552506    209
           ...
1.737926      1
1.727335      1
0.684087      1
1.073912      1
1.092971      1
Name: feature16, Length: 2991, dtype: int64
feature17
0.000000    229
0.890516     86
1.019202     67
1.282439     41
0.786865     39
           ...
1.057565      1
0.824962      1
0.769929      1
1.147551      1
0.916112      1
Name: feature17, Length: 12469, dtype: int64
feature18
810.6    4737
764.1    1601
772.0    1058
773.0     386
781.6     318
         ...
372.2       1
139.6       1
250.8       1
82.1        1
202.0       1
Name: feature18, Length: 816, dtype: int64
feature19
0.000000      229
738.769286    124
659.715385     89
661.026667     88
698.952308     60
             ...
384.353333      1
703.554923      1
241.083333      1
354.463333      1
204.564000      1
Name: feature19, Length: 10326, dtype: int64
feature20
311.743492    580
314.505966    281
276.063148    261
0.000000      232
282.395259    209
             ...
340.507822      1
272.992145      1
299.071821      1
264.479884      1
113.934266      1
Name: feature20, Length: 2950, dtype: int64
feature21
0.000000      231
342.396001     86
333.238432     67
255.465227     41
353.819831     39
             ...
345.594891      1
336.224636      1
254.790785      1
331.931653      1
351.146738      1
Name: feature21, Length: 12372, dtype: int64
feature22
164.500000    597
149.800000    374
160.000000    290
151.750000    282
167.000000    280
             ...
130.750000      1
117.600000      1
110.000000      1
114.333333      1
99.000000       1
Name: feature22, Length: 912, dtype: int64
feature23
114.538462    86
106.133333    72
157.000000    48
106.333333    44
104.371429    43
              ..
143.728246     1
110.192308     1
112.721151     1
104.580000     1
156.850000     1
Name: feature23, Length: 10492, dtype: int64
feature24
139.000514    580
131.302197    281
133.425311    261
139.595299    209
155.938199    191
             ...
164.696691      1
155.611696      1
98.270036       1
152.600422      1
140.082476      1
Name: feature24, Length: 2919, dtype: int64
feature25
89.685191     86
86.457339     72
103.149906    44
84.110835     43
153.255987    41
              ..
190.734854     1
87.604503      1
89.227981      1
164.772488     1
144.561871     1
Name: feature25, Length: 12409, dtype: int64
feature26
1.256701    580
1.275274    281
1.519537    261
0.000000    229
1.501218    209
           ...
0.678812      1
1.065034      1
1.064110      1
1.093802      1
1.875107      1
Name: feature26, Length: 2887, dtype: int64
feature27
0.000000    229
1.339743     86
1.573185     67
1.166832     41
0.689009     40
           ...
1.171852      1
1.688862      1
1.396798      1
1.592022      1
1.308795      1
Name: feature27, Length: 12393, dtype: int64
feature28
205    4889
171    2505
139     354
199     272
53      267
       ...
102       2
223       2
99        1
197       1
163       1
Name: feature28, Length: 192, dtype: int64
feature29
0.000000      230
65.428571     156
48.750000     102
38.500000      99
22.615385      86
             ...
60.236422       1
40.683333       1
48.043011       1
44.661429       1
146.543000      1
Name: feature29, Length: 9638, dtype: int64
feature30
77.525802    580
65.579627    281
58.608532    261
0.000000     244
69.922815    209
            ...
61.545828      1
58.980399      1
58.636060      1
73.554402      1
34.682689      1
Name: feature30, Length: 2365, dtype: int64
feature31
0.000000     244
79.235399     86
66.319295     72
27.341462     44
67.111458     43
            ...
68.038442      1
61.909574      1
49.179609      1
66.174891      1
79.392862      1
Name: feature31, Length: 11887, dtype: int64
feature32
4235.857250    580
4434.357250    281
4584.285800    261
4816.685800    209
4716.685800    191
              ...
5186.904833      1
4636.238167      1
5329.666667      1
5767.775571      1
5120.000000      1
Name: feature32, Length: 3027, dtype: int64
feature33
2952.461769     86
2953.428800     67
5481.918429     41
2961.473714     39
2219.333333     37
                ..
18228.320000     1
9597.900000      1
8181.000000      1
4051.000405      1
12288.000000     1
Name: feature33, Length: 12442, dtype: int64
feature34
669.556588     580
674.484751     281
874.164786     261
1074.903488    209
1059.408482    191
              ...
1424.689513      1
5212.674937      1
1159.138695      1
3030.708671      1
3813.787503      1
Name: feature34, Length: 3078, dtype: int64
feature35
66.342169      86
64.622881      67
1780.077447    41
53.427017      39
2190.987982    37
               ..
5431.744839     1
2445.658713     1
65.864862       1
4769.206119     1
3079.981970     1
Name: feature35, Length: 12494, dtype: int64
feature36
1.015407    580
0.995983    281
1.161774    261
0.000000    229
1.322213    209
           ...
1.348088      1
1.347882      1
0.831334      1
0.943487      1
0.516497      1
Name: feature36, Length: 3033, dtype: int64
feature37
0.000000    229
0.812798     86
1.099512     67
0.810985     41
0.769628     39
           ...
0.982631      1
1.203804      1
1.223592      1
1.124431      1
0.690941      1
Name: feature37, Length: 12489, dtype: int64
feature38
8958.571     5082
9778.571     1198
11338.571     581
13532.571     550
11848.571     495
             ...
3056.000        1
2922.000        1
5340.000        1
4053.000        1
8248.000        1
Name: feature38, Length: 842, dtype: int64
feature39
2066.922846    583
3839.795857    299
1303.237867    286
0.000000       230
1623.483429    191
              ...
2703.618400      1
1722.334942      1
7379.700000      1
2890.914706      1
4955.224000      1
Name: feature39, Length: 7833, dtype: int64
feature40
3194.938946    580
3402.856196    281
4004.273231    261
0.000000       240
3084.729342    209
              ...
1826.648175      1
5486.969433      1
2002.122124      1
2443.009665      1
3404.946500      1
Name: feature40, Length: 3016, dtype: int64
feature41
0.000000       239
3639.129247     86
3977.060817     67
3275.968307     41
3581.848921     39
              ...
1391.987425      1
2534.590559      1
3974.808407      1
817.777791       1
1438.363392      1
Name: feature41, Length: 12376, dtype: int64
feature42
77.237500     580
82.337500     411
79.607500     281
73.100000     261
72.090000     244
             ...
171.850000      1
103.942500      1
114.085000      1
76.350000       1
73.583333       1
Name: feature42, Length: 2233, dtype: int64
feature43
110.738462    217
113.271429    136
81.716667     104
109.169231     86
83.514286      72
             ...
122.870000      1
88.722625       1
159.719205      1
94.812191       1
104.918611      1

Name: feature43, Length: 11287, dtype: int64
feature44
53.527965    580
60.721493    411
48.477265    281
33.148783    261
53.116082    244
            ...
70.030001      1
79.700912      1
60.999342      1
70.141442      1
97.619465      1
Name: feature44, Length: 2481, dtype: int64
feature45
89.962916     139
103.947321    136
65.911020     104
86.539377      86
89.962916      78
             ...
70.252681       1
62.362171       1
87.006347       1
45.581424       1
35.167786       1
Name: feature45, Length: 11452, dtype: int64
feature46
1.105182    580
1.164013    411
1.096672    281
1.200886    261
1.357429    244
           ...
1.085728      1
1.057485      1
1.045346      1
0.813463      1
1.119062      1
Name: feature46, Length: 2440, dtype: int64
feature47
0.000000    229
0.802322    117
0.762761     86
0.827671     67
0.822661     65
           ...
0.680396      1
0.640253      1
0.384366      1
1.029405      1
1.131646      1
Name: feature47, Length: 11714, dtype: int64
feature48
127.05    2618
138.63    2307
135.97    1671
141.00    1340
127.20     260
          ...
39.50        1
36.80        1
64.60        1
135.70       1
43.90        1
Name: feature48, Length: 615, dtype: int64
feature49
0.000000     234
74.353846    215
75.742000    143
80.325000    120
81.288643    113
            ...
71.128125      1
77.311218      1
61.771200      1
36.355000      1
77.572931      1
Name: feature49, Length: 9232, dtype: int64
feature50
54.830755    580
51.125720    411
54.373097    281
57.645673    261
0.000000     248
            ...
61.950805      1
69.369205      1
45.602714      1
35.028655      1
36.348590      1
Name: feature50, Length: 2372, dtype: int64
feature51
0.000000     244
47.216641    217
39.807742    136
48.460823    104
49.445714     86
            ...
22.958704      1
65.073379      1
76.510793      1
22.802045      1
46.267729      1
Name: feature51, Length: 11313, dtype: int64
feature52
8.180500     591
6.905500     396
8.152400     261
8.014400     209
7.924400     191
            ...
18.396667      1
9.224400       1
33.450000      1
6.874571       1
10.530500      1
Name: feature52, Length: 2479, dtype: int64
feature53
5.250308     96
4.954400     67
9.560286     48
3.834714     46
5.438400     44
             ..
12.107508     1
3.877571      1
5.333067      1
23.303500     1
13.236595     1
Name: feature53, Length: 11834, dtype: int64
feature54
4.035569     591
3.479475     396
4.646433     261
4.549685     209
4.492557     191
            ...
16.141858      1
20.428016      1
7.769942       1
10.689879      1
35.945659      1
Name: feature54, Length: 2926, dtype: int64
feature55
1.336920     96
1.321875     67
6.229663     48
1.039211     46
1.381019     44
             ..
1.042344      1
22.833877     1
1.030321      1
1.318493      1
1.086420      1
Name: feature55, Length: 12257, dtype: int64
feature56
1.112098    591
1.088575    396
1.392937    261
0.000000    229
1.384657    209
           ...
0.956542      1
1.092254      1
0.899907      1
1.595425      1
1.081592      1
Name: feature56, Length: 2872, dtype: int64
feature57
0.000000    229
1.042927     86
1.395814     67
0.964031     46
0.975148     41
           ...
0.983535      1
1.402257      1
0.315223      1
0.884288      1
1.503184      1
Name: feature57, Length: 12338, dtype: int64
feature58
12.878     6239
27.478      465
13.578      357
15.978      292
16.978      283
           ...
22.242        1
1.700         1
12.050        1
101.740       1
38.700        1
Name: feature58, Length: 567, dtype: int64
feature59
2.903538     395
1.744571     383
5.582571     294
1.628267     243
0.000000     229
            ...
19.590000      1
2.931051       1
3.112933       1
15.333333      1
2.938267       1
Name: feature59, Length: 8223, dtype: int64
feature60
4.948155     591
4.599064     396
4.361026     261
0.000000     229
4.438215     209
            ...
19.734403      1
14.819341      1
5.879259       1
27.400000      1
4.961854       1
Name: feature60, Length: 2705, dtype: int64
feature61
0.000000     229
5.648557      96
5.253410      67
4.359650      48
4.658301      46
            ...
24.886339      1
13.097922      1
0.838523       1
6.268136       1
9.111814       1
Name: feature61, Length: 12036, dtype: int64
feature62
108.756645    694
89.605316     371
112.006645    289
128.605316    261
111.005316    217
             ...
19.258056       1
69.618083       1
56.256458       1
152.760940      1
109.205316      1
Name: feature62, Length: 1877, dtype: int64
feature63
96.398928     114
72.414176      68
71.333333      63
61.343760      50
179.003797     49
             ...
183.203797      1
60.813760       1
72.043376       1
92.837389       1
111.714286      1
Name: feature63, Length: 10990, dtype: int64
feature64
7.552385     694
8.418912     371
8.339818     289
14.287643    261
13.131173    217
            ...
1.811077       1
48.783671      1
15.067868      1
21.758991      1
6.895197       1
Name: feature64, Length: 2563, dtype: int64
feature65
1.096295     114
0.969156      68
26.578636     49
0.629441      49
0.614021      38
            ...
23.653201      1
1.117189       1
14.247260      1
0.947126       1
1.309895       1
Name: feature65, Length: 11769, dtype: int64
feature66
0.336262    694
0.457810    371
0.403693    289
0.871976    261
0.000000    229
           ...
1.045931      1
0.689965      1
0.911165      1
0.848341      1
1.056283      1
Name: feature66, Length: 2535, dtype: int64
feature67
0.000000    229
0.203148    114
0.777323     67
0.201966     49
0.283412     39
           ...
0.125364      1
0.807828      1
0.583091      1
0.204333      1
0.580268      1
Name: feature67, Length: 11872, dtype: int64
feature68
399.97342    8305
78.97342      340
133.00000     253
0.00000       243
99.97342      181
             ...
63.30000        1
70.97342        1
178.00000       1
35.55100        1
35.97342        1
Name: feature68, Length: 434, dtype: int64
feature69
57.127669     783
92.293380     583
53.319157     341
171.424774    299
0.000000      236
             ...
86.809633       1
92.060632       1
49.227000       1
56.434010       1
6.917641        1
Name: feature69, Length: 6819, dtype: int64
feature70
168.301047    694
155.329609    371
166.742351    289
154.008028    261
0.000000      243
             ...
7.350000        1
110.000000      1
182.616173      1
151.000000      1
167.418219      1
Name: feature70, Length: 2338, dtype: int64
feature71
0.000000      242
166.440383    114
137.579265     68
138.437714     49
191.475655     49
             ...
138.572787      1
36.842637       1
137.255914      1
166.256665      1
140.845546      1
Name: feature71, Length: 11485, dtype: int64
feature72
2.250000    1537
3.000000    1436
2.200000    1245
4.000000    1111
2.600000     998
            ...
4.400000       2
1.666667       2
5.750000       1
1.250000       1
1.333333       1
Name: feature72, Length: 63, dtype: int64
feature73
2.076923    508
2.000000    364
3.000000    314
5.000000    290
4.500000    290
           ...
2.107060      1
3.091667      1
2.436364      1
2.677256      1
2.146413      1
Name: feature73, Length: 4930, dtype: int64
feature74
2.213364    1525
2.168944    1230
2.491462     735
2.352158     703
2.000000     475
            ...
1.259921       1
2.598526       1
1.974350       1
3.222575       1
3.031433       1
Name: feature74, Length: 235, dtype: int64
feature75
2.063362    484
2.000000    354
6.000000    258
2.119268    205
3.000000    190
           ...
3.952851      1
2.197660      1
3.706352      1
2.069753      1
4.180095      1
Name: feature75, Length: 6865, dtype: int64
feature76
1.368922    1529
1.594167    1221
1.589027     703
1.564957     699
0.693147     469
            ...
1.791041       1
1.236685       1
1.898927       1
1.254099       1
1.343810       1
Name: feature76, Length: 309, dtype: int64
feature77
0.000000    229
1.201823    203
0.562335    166
0.636514    116
1.309526    101
           ...
1.134329      1
1.265422      1
0.793951      1
1.269896      1
1.323097      1
Name: feature77, Length: 9086, dtype: int64
feature78
1    5930
2    4088
3    3476
4    1847
0    1108
5     547
6       4
Name: feature78, dtype: int64
feature79
1.000000    400
0.000000    297
0.500000    230
0.846154    209
0.800000    160
           ...
2.566210      1
1.522500      1
3.391386      1
2.825000      1
0.999315      1
Name: feature79, Length: 5075, dtype: int64
feature80
0.433013    1557
0.400000    1267
0.500000    1110
0.000000    1108
0.471405     968
            ...
1.743560       1
0.638877       1
2.165064       1
1.884415       1
1.363589       1
Name: feature80, Length: 121, dtype: int64
feature81
0.000000    1008
0.266469     489
0.433013     333
0.471405     220
0.349927     216
            ...
0.687823       1
0.257723       1
0.471992       1
0.305566       1
1.177168       1
Name: feature81, Length: 6018, dtype: int64
critical_temperature
80.0000    118
20.0000    106
90.0000    105
30.0000    101
40.0000     91
          ...
2.3917       1
0.4760       1
27.8500      1
7.1340       1
0.0485       1
Name: critical_temperature, Length: 2778, dtype: int64

In [747]:
features = df1.drop('critical_temperature', axis = 1) 
labels = pd.DataFrame(df1['critical_temperature'], columns = ['critical_temperature'])

In [748]:
features

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature72,feature73,feature74,feature75,feature76,feature77,feature78,feature79,feature80,feature81
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.119000,20.285800,36.105357,...,4.250000,4.100000,4.053600,3.944244,1.339718,1.245504,3,1.400000,1.299038,1.135782
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.981000,25.192187,67.233835,...,2.600000,2.400000,2.402249,2.259897,1.519383,1.365077,3,0.933333,1.200000,1.019804
2,2,23.035850,26.647510,21.192566,25.010514,0.614232,0.435817,18.058300,18.243490,9.029150,...,4.500000,5.100000,4.242641,4.873514,0.636514,0.465999,3,3.300000,1.500000,1.374773
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.482000,28.789976,32.890369,...,3.500000,3.620000,3.309751,3.413039,1.333736,1.019322,3,1.920000,1.118034,1.198165
4,2,67.485250,69.699016,57.442709,59.574464,0.548263,0.521345,70.840500,39.638078,35.420250,...,6.000000,6.000000,6.000000,6.000000,0.693147,0.691193,0,0.375000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,3,72.816957,57.907791,52.075936,36.128407,0.838545,0.840863,122.906070,30.609277,50.602625,...,2.333333,2.285714,2.289428,2.245649,1.078992,0.974315,1,0.857143,0.471405,0.451754
16996,6,70.527467,91.385775,41.594713,59.041700,1.373685,1.177703,202.039400,51.551000,67.643464,...,2.333333,2.650000,2.075782,2.346454,1.668174,1.484840,4,1.150000,1.247219,1.388344
16997,2,145.650000,181.314000,138.659822,178.571988,0.645546,0.215090,89.160000,161.100000,44.580000,...,6.000000,6.000000,6.000000,6.000000,0.693147,0.325083,0,4.800000,0.000000,0.000000
16998,4,91.808100,56.820735,67.689303,37.015522,1.173514,1.329216,134.360600,13.116892,54.877137,...,2.250000,2.078555,2.213364,2.064728,1.368922,1.212753,1,0.821681,0.433013,0.269042
16999,5,76.392968,79.861421,71.435829,75.311863,1.535661,1.183003,82.388955,29.770863,31.312929,...,3.600000,3.633600,3.437544,3.426419,1.567056,1.067787,3,1.985600,1.019804,1.196725

In [749]:
labels

       critical_temperature
0                    21.500
1                    62.000
2                     0.290
3                    19.500
4                     5.360
...                     ...
16995                35.000
16996                89.000
16997                 0.584
16998                45.000
16999                13.500

[17000 rows x 1 columns]

In [750]:
df1_form = pd.read_csv("C:/formula_train.csv") 
df1_form.head(500)

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Eu1Fe1.5Ru0.5As2
1,0.0,0,0.0,0.0,0.0,0.0,0.0,8.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0,Bi2Sr2Ca1Cu2O8
2,0.0,0,0.0,0.0,0.0,0.0,0.3,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,N0.3S0.7
3,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Ba1Fe1.9Co0.1As2
4,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Rh17S15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.0,0,0.0,0.0,0.0,0.0,0.0,4.00,0.0,0,...,0.0,0.0,0.7,0.0,0.0,0.0,0,0,0,Hg0.7Cr0.3Sr2Cu0.9Ni0.1O4
496,0.0,0,0.0,0.0,0.0,0.0,0.0,6.45,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Y1Ba2Cu3O6.45
497,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,Pb1
498,0.0,0,0.0,0.0,0.0,0.0,0.0,7.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,Gd1Ba2Cu2.85Fe0.15O7
499,0.0,0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,La1Fe1P1O1

In [751]:
df2_form = pd.read_csv("C:/formula_test.csv") 
df2_form.head(500)

,H,He,Li,Be,B,C,N,O,F,Ne,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.000,0.00,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,La1Ba2Cu2.94Fe0.06O
1,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0,...,0.08,0.0,0.0,0.0,0.0,0.0,0,0,0,Sr1Pd1.92Pt0.08Ge2
2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Ba1Fe1.55Ru0.45As2
3,0.0,0,0.0,0.0,0.0,0.0,0.0,7.000,0.00,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Y1Ba2Cu2.97Fe0.03O7
4,0.0,0,0.0,0.0,0.0,0.0,0.0,4.000,0.00,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Pr1.85Ce0.15Cu1O4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000,0.00,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Sn0.923In0.065Te1
496,0.0,0,0.0,0.0,0.0,0.0,0.0,6.360,0.00,0,...,0.00,0.0,0.0,0.0,0.0,2.0,0,0,0,Bi2Sr2Cu1O6.36
497,0.0,0,0.0,0.0,0.0,0.0,0.0,8.181,0.00,0,...,0.00,0.0,0.0,0.0,0.0,2.0,0,0,0,Bi2Sr1.9Ca1.1Cu2O8.181
498,0.0,0,0.0,0.0,0.0,0.0,0.0,0.940,0.06,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,Sm1Fe1As1F0.06O0.94
499,0.0,0,0.0,0.0,0.0,60.0,0.0,0.000,0.00,0,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,C60Rb3

In [752]:
df1_form = df1_form.drop('material', axis=1)

In [753]:
df1_form

,H,He,Li,Be,B,C,N,O,F,Ne,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,0.0,0,0.0,0.0,0.0,0.0,0.0,8.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
2,0.0,0,0.0,0.0,0.0,0.0,0.3,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,0.0,0,0.0,0.0,0.0,0.0,0.0,4.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16996,0.0,0,0.8,0.0,0.0,0.0,0.0,1.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
16997,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16998,0.0,0,0.0,0.0,0.0,0.0,0.0,6.73,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16999,0.0,0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [754]:
df2_form = df2_form.drop('material', axis=1)

In [755]:
df2_form

,H,He,Li,Be,B,C,N,O,F,Ne,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
1,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.08,0.0,0.0,0.0,0.0,0.0,0,0,0
2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
3,0.0,0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4259,0.0,0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.2,1.8,0,0,0
4260,0.0,0,0.0,0.0,1.9,0.1,0.0,0.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4261,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,3.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4262,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0

In [756]:
res1 =  pd.merge(features,df1_form,right_index=True, left_index=True)

In [757]:
res1

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.119000,20.285800,36.105357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.981000,25.192187,67.233835,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
2,2,23.035850,26.647510,21.192566,25.010514,0.614232,0.435817,18.058300,18.243490,9.029150,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.482000,28.789976,32.890369,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,2,67.485250,69.699016,57.442709,59.574464,0.548263,0.521345,70.840500,39.638078,35.420250,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,3,72.816957,57.907791,52.075936,36.128407,0.838545,0.840863,122.906070,30.609277,50.602625,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16996,6,70.527467,91.385775,41.594713,59.041700,1.373685,1.177703,202.039400,51.551000,67.643464,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
16997,2,145.650000,181.314000,138.659822,178.571988,0.645546,0.215090,89.160000,161.100000,44.580000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16998,4,91.808100,56.820735,67.689303,37.015522,1.173514,1.329216,134.360600,13.116892,54.877137,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16999,5,76.392968,79.861421,71.435829,75.311863,1.535661,1.183003,82.388955,29.770863,31.312929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [758]:
res2 =  pd.merge(df2,df2_form,right_index=True, left_index=True)

In [759]:
res2

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,5,82.324574,88.533544,64.110667,72.640059,1.418486,1.179961,122.90607,38.757614,48.331141,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
1,4,115.438500,90.562624,107.211420,88.713057,1.308571,1.157701,122.45400,37.743936,47.516249,...,0.0,0.08,0.0,0.0,0.0,0.0,0.0,0,0,0
2,4,92.290900,83.842290,87.295606,79.318618,1.331889,1.300022,81.48200,20.872340,30.558629,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
3,5,72.324650,51.227894,58.637102,34.924853,1.444612,1.306314,121.32760,20.998358,40.053512,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4,4,90.142263,58.462879,66.935044,36.272055,1.178649,1.019134,124.90825,34.237393,53.101375,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,4,108.439500,115.102200,106.014678,113.022376,1.365649,1.116937,54.97000,54.614560,21.187340,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4259,6,103.903967,59.200661,73.259860,36.122054,1.511455,1.524380,192.98100,22.405781,76.817996,...,0.0,0.00,0.0,0.0,0.0,0.2,1.8,0,0,0
4260,3,15.708900,15.348990,14.668193,14.212349,1.027648,0.792486,13.49400,7.701310,6.098061,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4261,5,100.966814,72.804399,85.405861,66.049020,1.450286,1.384314,155.00600,29.741627,57.825886,...,0.0,3.00,0.0,0.0,0.0,0.0,0.0,0,0,0
4262,3,86.196460,74.958186,85.343532,74.312645,1.089048,0.593157,26.23700,55.406774,11.715014,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0

In [760]:
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition  import PCA

In [761]:
scaler = StandardScaler()

In [762]:
scaler.fit(res1)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [763]:
df1_dummies_scal = scaler.transform(res1)

In [764]:
res1

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.119000,20.285800,36.105357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.981000,25.192187,67.233835,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
2,2,23.035850,26.647510,21.192566,25.010514,0.614232,0.435817,18.058300,18.243490,9.029150,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.482000,28.789976,32.890369,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,2,67.485250,69.699016,57.442709,59.574464,0.548263,0.521345,70.840500,39.638078,35.420250,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,3,72.816957,57.907791,52.075936,36.128407,0.838545,0.840863,122.906070,30.609277,50.602625,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16996,6,70.527467,91.385775,41.594713,59.041700,1.373685,1.177703,202.039400,51.551000,67.643464,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
16997,2,145.650000,181.314000,138.659822,178.571988,0.645546,0.215090,89.160000,161.100000,44.580000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16998,4,91.808100,56.820735,67.689303,37.015522,1.173514,1.329216,134.360600,13.116892,54.877137,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16999,5,76.392968,79.861421,71.435829,75.311863,1.535661,1.183003,82.388955,29.770863,31.312929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [765]:
df1_dummies_scal

array([[-0.07808008,  0.28060954,  0.42128882, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.61796677, -0.14746506, -0.41241458, ...,  0.        ,
         0.        ,  0.        ],
       [-1.47017378, -2.17604546, -1.38248066, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.47017378,  1.95511489,  3.2231375 , ...,  0.        ,
         0.        ,  0.        ],
       [-0.07808008,  0.14105409, -0.48399027, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.61796677, -0.37831812,  0.20210922, ...,  0.        ,
         0.        ,  0.        ]])

In [766]:
pca = PCA(n_components=3)

In [767]:
pca.fit(df1_dummies_scal)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [768]:
X_pca = pca.transform(df1_dummies_scal)

In [769]:
dbscan = DBSCAN(eps=0.55)

In [770]:
new = dbscan.fit_predict(X_pca)

In [771]:
new

array([ 0,  1, -1, ..., -1,  1,  0], dtype=int64)

In [772]:
newdf = pd.DataFrame(new,  columns=['metka'])

In [773]:
feature_names2 = newdf.columns.tolist() 
for column in feature_names2: 
    print(column) 
    print(newdf[column].value_counts(dropna=False))

metka
 1      6556
 0      4034
 3      1345
-1      1298
 13      343
        ...
 195       5
 211       4
 136       4
 214       4
 215       4
Name: metka, Length: 224, dtype: int64

In [774]:
res1['metka']=new

In [775]:
labels['metka']=new

In [776]:
res1 = res1.loc[res1['metka'] != -1]

In [777]:
labels = labels.loc[labels['metka'] != -1]

In [778]:
res1 = res1.drop('metka', axis=1)

In [779]:
labels = labels.drop('metka', axis=1)

In [780]:
res1

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,95.950150,87.221940,89.534122,81.423258,1.317590,1.301059,96.119000,20.285800,36.105357,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,83.244760,59.224400,59.506081,36.126175,1.311510,1.372050,192.981000,25.192187,67.233835,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
3,4,81.756699,79.833804,76.282833,75.275775,1.312596,1.149324,81.482000,28.789976,32.890369,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
5,2,87.767750,90.795300,86.452452,89.517835,0.678199,0.626849,30.275500,32.691300,15.137750,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
6,3,87.511127,77.600095,81.507104,71.351918,1.034263,1.090931,73.893000,7.213405,30.406967,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16994,5,87.613160,91.935539,66.815634,74.326570,1.401760,1.186644,146.500600,38.817047,54.080710,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16995,3,72.816957,57.907791,52.075936,36.128407,0.838545,0.840863,122.906070,30.609277,50.602625,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16996,6,70.527467,91.385775,41.594713,59.041700,1.373685,1.177703,202.039400,51.551000,67.643464,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0
16998,4,91.808100,56.820735,67.689303,37.015522,1.173514,1.329216,134.360600,13.116892,54.877137,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
16999,5,76.392968,79.861421,71.435829,75.311863,1.535661,1.183003,82.388955,29.770863,31.312929,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [781]:
pca.fit(df1_dummies_scal)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [782]:
scaler = StandardScaler()

In [783]:
scaler.fit(res1)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [784]:
df1_dummies_scal = scaler.transform(res1)

In [785]:
pca = PCA(n_components=2)

In [786]:
pca.fit(df1_dummies_scal)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [787]:
X_pca = pca.transform(df1_dummies_scal)

In [788]:
kmeans = KMeans(n_clusters=5, random_state=0)

In [789]:
res = kmeans.fit(X_pca)

In [790]:
res.labels_

array([1, 0, 1, ..., 0, 4, 1])

In [791]:
res_df = pd.DataFrame({'cluster' : res.labels_})

In [792]:
feature_names2 = res_df.columns.tolist() 
for column in feature_names2: 
    print(column) 
    print(res_df[column].value_counts(dropna=False))

cluster
0    4824
4    4641
1    2620
3    2429
2    1188
Name: cluster, dtype: int64

In [793]:
res1['cluster'] =  res.labels_

In [794]:
df2_dummies_scal = scaler.transform(res2)

In [795]:
X_pca2 = pca.transform(df2_dummies_scal)

In [796]:
res22 = kmeans.predict(X_pca2)

In [797]:
res2['cluster'] =  res22

In [798]:
res2

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn,cluster
0,5,82.324574,88.533544,64.110667,72.640059,1.418486,1.179961,122.90607,38.757614,48.331141,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,0
1,4,115.438500,90.562624,107.211420,88.713057,1.308571,1.157701,122.45400,37.743936,47.516249,...,0.08,0.0,0.0,0.0,0.0,0.0,0,0,0,1
2,4,92.290900,83.842290,87.295606,79.318618,1.331889,1.300022,81.48200,20.872340,30.558629,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,1
3,5,72.324650,51.227894,58.637102,34.924853,1.444612,1.306314,121.32760,20.998358,40.053512,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,4
4,4,90.142263,58.462879,66.935044,36.272055,1.178649,1.019134,124.90825,34.237393,53.101375,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,4,108.439500,115.102200,106.014678,113.022376,1.365649,1.116937,54.97000,54.614560,21.187340,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,1
4259,6,103.903967,59.200661,73.259860,36.122054,1.511455,1.524380,192.98100,22.405781,76.817996,...,0.00,0.0,0.0,0.0,0.2,1.8,0,0,0,0
4260,3,15.708900,15.348990,14.668193,14.212349,1.027648,0.792486,13.49400,7.701310,6.098061,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,2
4261,5,100.966814,72.804399,85.405861,66.049020,1.450286,1.384314,155.00600,29.741627,57.825886,...,3.00,0.0,0.0,0.0,0.0,0.0,0,0,0,1
4262,3,86.196460,74.958186,85.343532,74.312645,1.089048,0.593157,26.23700,55.406774,11.715014,...,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0,3

In [799]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.feature_selection import RFE
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition  import PCA
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import StratifiedKFold

In [540]:
pipe = Pipeline([("scaler", StandardScaler()), ('PCA', PCA(n_components=75)), ('GBoost', GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=0.24, random_state=42))])

In [4244]:
pipe2 = Pipeline([("scaler", StandardScaler()), ('PCA', PCA(n_components=70)), ('GBoost', GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=0.24, random_state=42))])

In [4245]:
pipe3 = Pipeline([("scaler", StandardScaler()), ('PCA', PCA(n_components=93)), ('GBoost', GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=0.28, random_state=0))])

In [960]:
pipe4 = Pipeline([("scaler", StandardScaler()), ('PCA', PCA(n_components=164)), ('GBoost', GradientBoostingRegressor(n_estimators=100, max_depth=5, learning_rate=0.24, random_state=392))])

In [4247]:
param_grid = {
    'GBoost__learning_rate': [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
}

In [4248]:
grid = GridSearchCV(pipe2, param_grid, cv=5)

In [4249]:
rand = RandomizedSearchCV(pipe4, param_grid, cv=)

In [4250]:
rand.fit(res1, labels)

KeyboardInterrupt:

In [4059]:
rand.best_params_

{'GBoost__learning_rate': 0.24}

In [4060]:
rand.best_score_

0.9055725156096075

In [4053]:
pipe2.score(features, labels)

NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [961]:
pipe4.fit(res1, labels)

Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('PCA',
                 PCA(copy=True, iterated_power='auto', n_components=164,
                     random_state=None, svd_solver='auto', tol=0.0,
                     whiten=False)),
                ('GBoost',
                 GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse',
                                           init=None, learning_rate=0.24,
                                           loss='ls', max_depth=5,
                                           max_features=None,
                                           max_leaf_nodes=None,
                                           min_impurity_decrease=0.0,
                                           min_impurity_split=None,
                                           min_samples_leaf=1,
                                           min_samples_split=2,
                                           min_weight_fraction_leaf=0.0,
                                           n_estimators=100,
                                           n_iter_no_change=None,
                                           presort='auto', random_state=392,
                                           subsample=1.0, tol=0.0001,
                                           validation_fraction=0.1, verbose=0,
                                           warm_start=False))],
         verbose=False)

In [962]:
lol = pipe4.predict(res2)

In [963]:
res4 = pd.DataFrame()

In [964]:
res4['lol'] = lol

In [1018]:
res3

,lol1,lol2,lol3,lol4,lol5,lol6,lol7,lol8,lol9,lol10,...,lol21,lol22,lol23,lol24,lol25,lol26,lol27,lol28,lol29,lol30
0,52.992299,55.008497,55.008497,55.008497,55.008497,55.008497,55.008497,55.008497,55.008497,55.008497,...,52.992299,55.008497,55.008497,55.008497,52.992299,55.008497,55.008497,55.008497,55.008497,55.008497
1,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,...,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192,4.637192
2,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,...,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404,15.876404
3,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,...,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053,82.449053
4,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,...,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486,19.636486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,...,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232,2.875232
4259,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,...,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606,83.113606
4260,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,...,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425,34.242425
4261,33.615917,33.615917,30.255361,33.615917,33.615917,33.615917,33.615917,28.702700,33.615917,30.255361,...,33.615917,30.255361,30.255361,33.615917,30.255361,33.615917,28.702700,33.615917,33.615917,30.255361
4262,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,...,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389,7.064389

In [965]:
res4

            lol
0     55.008497
1      4.637192
2     15.876404
3     82.449053
4     19.636486
...         ...
4258   2.875232
4259  83.113606
4260  34.242425
4261  28.702700
4262   7.064389

[4263 rows x 1 columns]

In [1014]:
gboost = GradientBoostingRegressor(n_estimators=23)

In [1015]:
gboost.fit(res3, res4)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=23,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [1016]:
gboost.score(res3, res4)

0.9907238952372598

In [1017]:
gboost.predict(res3)

array([53.45904097,  7.23696044, 17.180673  , ..., 33.52544917,
       29.77052725,  9.10067029])

In [541]:
scores = cross_val_score(pipe4, res1, labels, cv=5)

In [542]:
scores.mean()

0.9037412650195373

In [ ]:
0.9028595248622014

In [ ]:
0.9057608411560143 0.55

In [ ]:
0.8997589940761055    8

In [ ]:
0.8989291808650932      6

In [ ]:
0.9004649256110797        5 при xy

In [ ]:
0.8998436988263012   5 xyz

In [ ]:
0.8986074330058562  2

In [ ]:
0.8988786665060969 11

In [ ]:
0.8998949377289808 без кластеров

In [1019]:
y_test_res = gboost.predict(res3)

In [1020]:
check_test = pd.DataFrame({'y_test_res' : y_test_res})

In [1021]:
check_test.head(10)

   y_test_res
0   53.459041
1    7.236960
2   17.180673
3   77.991071
4   20.997974
5   93.369645
6   41.366118
7    6.534380
8    9.923600
9   73.559760

In [1022]:
feature_names2 = check_test.columns.tolist() 
for column in feature_names2: 
    print(column) 
    print(check_test[column].value_counts(dropna=False))

y_test_res
9.923600     114
5.442516      99
8.565831      98
3.963947      91
7.871115      84
            ...
22.978871      1
29.903880      1
18.814853      1
19.486030      1
11.792989      1
Name: y_test_res, Length: 292, dtype: int64

In [1023]:
check_test.to_csv("D:/answer.csv", header=False, index=False)